# Generated by Django 5.0.6 on 2025-12-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_pgproperty_address_pgproperty_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgproperty',
            name='area',
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='area_road',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='gender_availability',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('both', 'Both Male & Female')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='has_laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='has_power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='rules',
            field=models.TextField(blank=True, help_text='Rules and regulations for the PG'),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
