# Generated by Django 5.0.6 on 2026-01-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_room_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Boys Hostel'), ('Female', 'Girls Hostel'), ('Both', 'Both Girls & Boys Hostel')], max_length=10)),
                ('wifi', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('housekeeping', models.BooleanField(default=False)),
                ('ro_water', models.BooleanField(default=False)),
                ('games', models.BooleanField(default=False)),
                ('hotwater', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('wardrobe', models.BooleanField(default=False)),
                ('studytable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='owner.hostel')),
            ],
        ),
    ]
