# Generated by Django 5.0.6 on 2026-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_hostel_hostelrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hostel_images/'),
        ),
    ]
