# Generated by Django 5.0.6 on 2026-01-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_hostel_hostel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgproperty',
            name='gender_availability',
            field=models.CharField(choices=[('Male', 'Boys Hostel'), ('Female', 'Girls Hostel'), ('Both', 'Both Girls & Boys Hostel')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='image',
            field=models.ImageField(upload_to='media/pg_images/'),
        ),
    ]
