# Generated by Django 5.0.6 on 2026-01-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_pgproperty_gender_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgproperty',
            name='gender_availability',
            field=models.CharField(choices=[('Male', 'Boys Hostel'), ('Female', 'Girls Hostel'), ('Both', 'Both Girls & Boys Hostel')], default='Both', max_length=10),
        ),
    ]
