# Generated by Django 5.0.6 on 2026-01-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_alter_pgproperty_gender_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_hostels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='gender_availability',
            field=models.CharField(choices=[('Male', 'Boys PG'), ('Female', 'Girls PG'), ('Both', 'Both Girls & Boys PG ')], default='Both', max_length=10),
        ),
    ]
