# Generated by Django 5.0.6 on 2026-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_hostel_owner_alter_pgproperty_gender_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
