# Generated by Django 5.0.6 on 2026-01-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_hostel_is_active_hostel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.hostel'),
        ),
    ]
