# Generated by Django 5.0.6 on 2026-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_booking_age_booking_email_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('Boys', 'Boys Hostel'), ('Girls', 'Girls Hostel'), ('Both Girls & Boys', 'Both Girls & Boys Hostel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='gender_availability',
            field=models.CharField(choices=[('Boys', 'Boys PG'), ('Girls', 'Girls PG'), ('Both Girls & Boys', 'Both Girls & Boys PG ')], default='Both', max_length=20),
        ),
    ]
