# Generated by Django 5.0.6 on 2026-01-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_alter_hostel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hostel_images/title/'),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='image',
            field=models.ImageField(upload_to='media/pg_images/title/'),
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/hostel_images/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='owner.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='PGPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/pg_images/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pg_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='owner.pgproperty')),
            ],
        ),
    ]
