# Generated by Django 5.0.6 on 2026-01-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_alter_hostel_hostel_image_alter_pgproperty_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgproperty',
            old_name='image',
            new_name='title_image',
        ),
    ]
