# Generated by Django 5.0.6 on 2026-01-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_rename_image_pgproperty_title_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='hostel_image',
            new_name='title_image',
        ),
    ]
