# Generated by Django 5.0.6 on 2026-01-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_rename_hostel_image_hostel_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
