# Generated by Django 5.0.6 on 2026-01-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='identity_proof',
            field=models.ImageField(blank=True, null=True, upload_to='media/identity_proofs/'),
        ),
    ]
