# Generated by Django 5.0.6 on 2025-12-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Owner', 'Owner')], default='Tenant', max_length=10),
        ),
    ]
