# Generated by Django 5.0.6 on 2025-12-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
    ]
