# Generated by Django 5.0.6 on 2025-12-29 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_identity_proof_userprofile_kyc_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Tenant', 'Tenant'), ('Owner', 'Owner')], default='Tenant', max_length=10)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('identity_proof', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('ownership_proof', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('kyc_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
    ]
