# Generated by Django 5.0.6 on 2025-12-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20251229_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
