# Generated by Django 5.0.6 on 2026-01-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20251229_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='media/kyc/'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='media/kyc/'),
        ),
    ]
