# Generated by Django 5.0.6 on 2025-12-10 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('owner_type', models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='pg_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_hostels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
