# Generated by Django 5.0.6 on 2025-12-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pghostel',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pghostel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='pghostel',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pghostel',
            name='total_rooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.pghostel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(limit_choices_to={'profile__role': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
    ]
