# Generated by Django 5.0.6 on 2025-12-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pgproperty_room_booking_delete_pghostels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgproperty',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='room',
            name='pg_property',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='PGProperty',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
