# Generated by Django 5.0.6 on 2026-01-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
